import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
import { SUPABASE_URL, SUPABASE_ANON_KEY } from './config.js';

const client = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

const params = new URLSearchParams(window.location.search);
const publicSlug = params.get('slug');
const staffParam = (params.get('staff') || '').trim();
const modeParam = params.get('mode');

// Two modes only (see the file header comment in the task/README):
//  - Preview mode: no staff/mode params (or mode !== 'solve') — read-only,
//    nothing is ever written to the DB. Reached from the Exam Dashboard.
//  - Solve mode: staff number + mode=solve — the real, submittable exam.
//    Reached ONLY via a link generated by the registration gate
//    (js/workshops.js) — there is no way to construct this from the
//    dashboard, by design.
const solveMode = !!staffParam && modeParam === 'solve';
const previewMode = !solveMode;

let exam = null;
let examQuestionsCache = [];
let examContentsCache = [];
let currentAttempt = null; // the activity_exam_attempts row, solve mode only
let countdownTimer = null;
let registrationToken = null; // private registration-link token of this exam's activity (best effort)
let autoSubmitting = false;

// Same small HSL helpers as js/evaluation-public.js / js/workshops.js.
function hexToHsl(hex) {
    hex = (hex || '').replace('#', '');
    if (hex.length === 3) hex = hex.split('').map(c => c + c).join('');
    if (!/^[0-9a-f]{6}$/i.test(hex)) return null;
    const r = parseInt(hex.substring(0, 2), 16) / 255;
    const g = parseInt(hex.substring(2, 4), 16) / 255;
    const b = parseInt(hex.substring(4, 6), 16) / 255;
    const max = Math.max(r, g, b), min = Math.min(r, g, b);
    let h, s, l = (max + min) / 2;
    if (max === min) {
        h = s = 0;
    } else {
        const d = max - min;
        s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
        switch (max) {
            case r: h = (g - b) / d + (g < b ? 6 : 0); break;
            case g: h = (b - r) / d + 2; break;
            default: h = (r - g) / d + 4;
        }
        h /= 6;
    }
    return { h: h * 360, s: s * 100, l: l * 100 };
}
function hslToHex(h, s, l) {
    h /= 360; s /= 100; l /= 100;
    let r, g, b;
    if (s === 0) {
        r = g = b = l;
    } else {
        const hue2rgb = (p, q, t) => {
            if (t < 0) t += 1;
            if (t > 1) t -= 1;
            if (t < 1 / 6) return p + (q - p) * 6 * t;
            if (t < 1 / 2) return q;
            if (t < 2 / 3) return p + (q - p) * (2 / 3 - t) * 6;
            return p;
        };
        const q = l < 0.5 ? l * (1 + s) : l + s - l * s;
        const p = 2 * l - q;
        r = hue2rgb(p, q, h + 1 / 3);
        g = hue2rgb(p, q, h);
        b = hue2rgb(p, q, h - 1 / 3);
    }
    const toHex = v => Math.round(v * 255).toString(16).padStart(2, '0');
    return `#${toHex(r)}${toHex(g)}${toHex(b)}`;
}
function shadeColor(hex, lightnessDeltaPct) {
    const hsl = hexToHsl(hex);
    if (!hsl) return hex;
    const l = Math.min(96, Math.max(6, hsl.l + lightnessDeltaPct));
    return hslToHex(hsl.h, hsl.s, l);
}

function applyExamTheme(rawColor) {
    const base = /^#([0-9a-f]{3}|[0-9a-f]{6})$/i.test(rawColor || '') ? rawColor : '#7C3AED';
    const root = document.documentElement.style;
    root.setProperty('--course-theme', base);
    root.setProperty('--course-theme-light', shadeColor(base, 16));
    root.setProperty('--course-theme-dark', shadeColor(base, -16));
    document.body.classList.remove('theme-loading');
}

function showFatalError(message) {
    document.getElementById('examFatalError').textContent = message;
    document.getElementById('examFatalError').classList.remove('hidden-element');
}

// ============================================================================
// Grading — shared by manual Submit, auto-submit-on-timeout, and the
// best-effort grade-on-resume-if-expired path. Per-type rules match the
// per-type correct_answer shape documented on activity_exam_questions in
// sql/activity-exams.sql. A missing/empty answer is simply ungraded
// (0 points, not correct) rather than an error — a partial submission
// (whatever was answered before the timer ran out) is expected and normal.
// ============================================================================
function normStr(s) { return String(s ?? '').trim().toLowerCase(); }

function gradeExamAnswer(question, answerValue) {
    const type = question.question_type;
    const correct = question.correct_answer;
    const points = Number(question.points) || 0;

    // A 0-point question is excluded from grading entirely — `is_correct`
    // is null (not false), so downstream displays/exports can tell "wasn't
    // graded" apart from "graded and wrong" (see sql/activity-exams.sql's
    // comment on activity_exam_answers.is_correct).
    if (points === 0) return { is_correct: null, points_earned: 0 };

    if (correct == null || answerValue == null) return { is_correct: false, points_earned: 0 };

    let isCorrect = false;
    if (type === 'text' || type === 'time' || type === 'date' || type === 'multiple_choice' || type === 'list') {
        isCorrect = normStr(answerValue) === normStr(correct);
    } else if (type === 'checkbox') {
        const given = Array.isArray(answerValue) ? answerValue.map(normStr).sort() : [];
        const want = Array.isArray(correct) ? correct.map(normStr).sort() : [];
        isCorrect = want.length > 0 && given.length === want.length && given.every((v, i) => v === want[i]);
    } else if (type === 'multiple_choice_grid') {
        const given = (answerValue && typeof answerValue === 'object') ? answerValue : {};
        const want = (correct && typeof correct === 'object') ? correct : {};
        const wantKeys = Object.keys(want);
        isCorrect = wantKeys.length > 0 && wantKeys.every(row => normStr(given[row]) === normStr(want[row]));
    } else if (type === 'checkbox_grid') {
        const given = (answerValue && typeof answerValue === 'object') ? answerValue : {};
        const want = (correct && typeof correct === 'object') ? correct : {};
        const wantKeys = Object.keys(want);
        isCorrect = wantKeys.length > 0 && wantKeys.every(row => {
            const g = Array.isArray(given[row]) ? given[row].map(normStr).sort() : [];
            const w = Array.isArray(want[row]) ? want[row].map(normStr).sort() : [];
            return w.length > 0 && g.length === w.length && g.every((v, i) => v === w[i]);
        });
    }
    return { is_correct: isCorrect, points_earned: isCorrect ? points : 0 };
}

async function init() {
    if (!publicSlug) {
        showFatalError('This exam link is invalid or incomplete.');
        return;
    }

    const { data, error } = await client
        .from('activity_exams')
        .select('*, courses(name)')
        .eq('public_slug', publicSlug)
        .maybeSingle();

    if (error || !data) {
        showFatalError('This exam link could not be found. Please check the link and try again.');
        return;
    }

    exam = data;
    document.getElementById('examPageTitle').textContent = exam.title;
    document.getElementById('examPageActivity').textContent = exam.courses?.name || 'Exam';
    applyExamTheme(exam.theme_color);

    if (exam.comment && exam.comment.trim()) {
        const commentEl = document.getElementById('examComment');
        commentEl.textContent = exam.comment;
        commentEl.classList.remove('hidden-element');
    }

    const [{ data: questions }, { data: contents }] = await Promise.all([
        client.from('activity_exam_questions').select('*').eq('exam_id', exam.id).order('display_order', { ascending: true }),
        client.from('activity_exam_contents').select('*').eq('exam_id', exam.id).order('content_order', { ascending: true })
    ]);
    examQuestionsCache = questions || [];
    examContentsCache = contents || [];

    if (previewMode) {
        document.getElementById('examPreviewBanner').classList.remove('hidden-element');
        startExamView();
        return;
    }

    // Best effort: the activity's private registration token, only used to build the way back
    // to its registration form. Missing column (SQL not run yet) just means the old link style.
    try {
        const { data: tokRow } = await client.from('courses').select('registration_token, links_closed').eq('id', exam.course_id).maybeSingle();
        if (tokRow) {
            registrationToken = tokRow.registration_token || null;
            exam.__courseClosed = tokRow.links_closed === true;
        }
    } catch (e) { /* ignore */ }

    // Who may take the exam for real:
    //  - a pre-registration exam: anyone with the link, but not once the activity is closed
    //    (nobody can register in a closed activity, so there is nothing for the exam to unlock);
    //  - any other exam (post-test...): only a staff number REGISTERED for this activity.
    if (exam.require_before_registration) {
        if (exam.__courseClosed) {
            showFatalError('Registration for this activity is closed.');
            return;
        }
    } else {
        const { data: regRows, error: regErr } = await client
            .from('registrations')
            .select('id')
            .eq('course_id', exam.course_id)
            .ilike('staff_number', escapeLike(staffParam))
            .limit(1);
        if (regErr) {
            showFatalError('Something went wrong checking your registration. Please try again.');
            return;
        }
        if (!regRows || regRows.length === 0) {
            showFatalError('This staff number is not registered for this activity, so it cannot take this exam. Please use the staff number you registered with.');
            return;
        }
    }

    await startSolveMode();
}

// ============================================================================
// Question rendering — same markup/CSS classes as js/evaluation-public.js
// (cq-* classes), reused for layout consistency. In preview mode every
// input is disabled and nothing is ever collected or submitted.
// ============================================================================
// Value placed inside an HTML attribute (value="…", data-row="…", name="…").
// An option / grid row / grid column containing a double quote used to cut the
// attribute short — the answer was then saved truncated (e.g. He said "yes"
// -> He said ), graded wrong, and a list option like "Q" could never be
// answered at all. Escaped, the browser hands back the exact original text.
function escapeAttr(v) {
    return String(v ?? '')
        .replace(/&/g, '&amp;')
        .replace(/"/g, '&quot;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;');
}

function renderExamQuestions() {
    const box = document.getElementById('examQuestionsContainer');
    const disabledAttr = previewMode ? 'disabled' : '';
    box.innerHTML = examQuestionsCache.map((q, index) => {
        const options = Array.isArray(q.options) ? q.options : [];
        const gridRows = Array.isArray(q.grid_rows) ? q.grid_rows : [];
        const gridCols = Array.isArray(q.grid_columns) ? q.grid_columns : [];
        let fieldHtml = '';

        if (q.question_type === 'text') {
            fieldHtml = `<input type="text" class="cq-answer-input" data-qid="${q.id}" ${disabledAttr}>`;
        } else if (q.question_type === 'date') {
            fieldHtml = `<input type="date" class="cq-answer-input" data-qid="${q.id}" ${disabledAttr}>`;
        } else if (q.question_type === 'time') {
            fieldHtml = `<input type="time" class="cq-answer-input" data-qid="${q.id}" ${disabledAttr}>`;
        } else if (q.question_type === 'list') {
            fieldHtml = `<select class="cq-answer-input" data-qid="${q.id}" ${disabledAttr}>
                <option value="">-- Select --</option>
                ${options.map(o => `<option value="${escapeAttr(o)}">${o}</option>`).join('')}
            </select>`;
        } else if (q.question_type === 'multiple_choice') {
            fieldHtml = options.map(o => `
                <label class="cq-choice-label">
                    <input type="radio" name="cq_${q.id}" class="cq-answer-radio" data-qid="${q.id}" value="${escapeAttr(o)}" ${disabledAttr}>
                    ${o}
                </label>`).join('');
        } else if (q.question_type === 'checkbox') {
            fieldHtml = options.map(o => `
                <label class="cq-choice-label">
                    <input type="checkbox" class="cq-answer-checkbox" data-qid="${q.id}" value="${escapeAttr(o)}" ${disabledAttr}>
                    ${o}
                </label>`).join('');
        } else if (q.question_type === 'multiple_choice_grid' || q.question_type === 'checkbox_grid') {
            const inputType = q.question_type === 'multiple_choice_grid' ? 'radio' : 'checkbox';
            fieldHtml = `
                <div class="cq-grid-scroll-wrapper">
                <table class="cq-grid-table">
                    <thead><tr><th></th>${gridCols.map(c => `<th>${c}</th>`).join('')}</tr></thead>
                    <tbody>
                        ${gridRows.map(row => `
                            <tr>
                                <td class="cq-grid-row-label">${row}</td>
                                ${gridCols.map(col => `
                                    <td><input type="${inputType}" name="cq_${q.id}_${escapeAttr(row)}" class="cq-answer-grid" data-qid="${q.id}" data-row="${escapeAttr(row)}" value="${escapeAttr(col)}" ${disabledAttr}></td>
                                `).join('')}
                            </tr>
                        `).join('')}
                    </tbody>
                </table>
                </div>`;
        }

        const isInlineType = ['text', 'date', 'time', 'list'].includes(q.question_type);
        const pointsBadge = q.points != null ? ` <span style="color:#94a3b8; font-weight:600; font-size:12px;">(${q.points} pt${Number(q.points) === 1 ? '' : 's'})</span>` : '';

        return `
            <div id="examQStepWrapper_${index}" class="hidden-element">
                <div class="cq-registration-field${isInlineType ? ' cq-inline-field' : ''}">
                    <label class="cq-question-text"><span class="cq-question-number">${index + 1}</span>${q.question_text}${pointsBadge}</label>
                    ${fieldHtml}
                </div>
            </div>
        `;
    }).join('');
}

// ============================================================================
// Step-through — same paging idea as js/evaluation-public.js's
// buildEvalPageSegments/goToEvalPage, renamed for the exam page. Unlike the
// evaluation, Next/Submit here never blocks on unanswered questions — a
// partial exam (whatever got answered before time ran out) is expected and
// valid to submit.
// ============================================================================
let examPageSegments = [[]];
let examPageIdx = 0;
let examStepIndex = 0;
let examBatchIndex = 0;

function buildExamPageSegments(contents, questions) {
    const maxPage = Math.max(
        questions.reduce((max, q) => Math.max(max, q.page_number || 1), 1),
        (contents || []).reduce((max, c) => Math.max(max, c.page_number || 1), 1)
    );
    const segments = [];
    for (let p = 1; p <= maxPage; p++) {
        const steps = [];
        const pageContents = (contents || []).filter(c => (c.page_number || 1) === p);
        if (pageContents.length) steps.push({ type: 'content_batch', items: pageContents });
        for (let k = 0; k < questions.length; k++) {
            if ((questions[k].page_number || 1) !== p) continue;
            steps.push({ type: 'question', index: k });
        }
        segments.push(steps);
    }
    return segments.length > 0 ? segments : [[]];
}

function advanceExamPageSteps() {
    const steps = examPageSegments[examPageIdx] || [];
    while (examStepIndex < steps.length) {
        const step = steps[examStepIndex];
        if (step.type === 'content_batch') {
            examBatchIndex = 0;
            showExamContentBatch(step.items);
            return;
        }
        if (step.type === 'question') {
            const el = document.getElementById('examQStepWrapper_' + step.index);
            if (el) el.classList.remove('hidden-element');
        }
        examStepIndex++;
    }
    updateExamPageNav();
}

function updateExamPageNav() {
    const nav = document.getElementById('examPageNavContainer');
    const prevBtn = document.getElementById('examPagePrevBtn');
    const nextBtn = document.getElementById('examPageNextBtn');
    const submitBtn = document.getElementById('examSubmitBtn');
    const isLast = examPageIdx === examPageSegments.length - 1;

    if (examPageSegments.length <= 1) {
        if (nav) nav.classList.add('hidden-element');
        if (!previewMode) submitBtn.classList.remove('hidden-element');
        return;
    }

    prevBtn.classList.toggle('hidden-element', examPageIdx === 0);
    nextBtn.classList.toggle('hidden-element', isLast);
    submitBtn.classList.toggle('hidden-element', previewMode || !isLast);
    if (nav) nav.classList.remove('hidden-element');

    prevBtn.onclick = () => {
        if (examPageIdx === 0) return;
        goToExamPage(examPageIdx - 1);
    };
    nextBtn.onclick = () => {
        if (examPageIdx >= examPageSegments.length - 1) return;
        // On an exam where every question must be answered (anything that is
        // not a pre-registration exam), the next page only opens once every
        // question on THIS page is answered — and the missing ones are named.
        if (!previewMode && examNeedsAllAnswers()) {
            const missing = missingQuestionNumbersOnPage(examPageIdx);
            if (missing.length > 0) {
                const errBox = document.getElementById('examSubmitError');
                errBox.textContent = `Please answer every question on this page before continuing. Not answered yet: question ${missing.join(', ')}.`;
                errBox.classList.remove('hidden-element');
                const firstWrapper = document.getElementById('examQStepWrapper_' + (missing[0] - 1));
                if (firstWrapper && firstWrapper.scrollIntoView) firstWrapper.scrollIntoView({ behavior: 'smooth', block: 'center' });
                return;
            }
        }
        document.getElementById('examSubmitError').classList.add('hidden-element');
        goToExamPage(examPageIdx + 1);
    };
}

// Question numbers (as shown to the participant) on the given page that have
// no answer yet.
function missingQuestionNumbersOnPage(pageIdx) {
    const steps = examPageSegments[pageIdx] || [];
    const indexes = steps.filter(st => st.type === 'question').map(st => st.index);
    const answered = new Set(collectExamAnswers().filter(a => isAnswerFilled(a.answer_value)).map(a => a.question_id));
    return indexes.filter(i => !answered.has(examQuestionsCache[i].id)).map(i => i + 1);
}

function goToExamPage(pageIdx) {
    document.querySelectorAll('[id^="examQStepWrapper_"]').forEach(el => el.classList.add('hidden-element'));
    examPageIdx = pageIdx;
    examStepIndex = 0;
    updateExamPageHeading();
    advanceExamPageSteps();
}

function updateExamPageHeading() {
    const headingEl = document.getElementById('examPageHeading');
    const wrapperEl = document.getElementById('examPageHeadingWrapper') || headingEl;
    if (!headingEl || !wrapperEl) return;
    const pageTitles = (exam && exam.page_titles && typeof exam.page_titles === 'object') ? exam.page_titles : {};
    const title = pageTitles[String(examPageIdx + 1)];
    if (title && title.trim()) {
        headingEl.textContent = title;
        wrapperEl.classList.remove('hidden-element');
    } else {
        headingEl.textContent = '';
        wrapperEl.classList.add('hidden-element');
    }
}

function showExamContentBatch(items) {
    const viewer = document.getElementById('examContentViewer');
    const total = items.length;
    const current = items[examBatchIndex];

    document.getElementById('examContentIndicator').textContent = `Content ${examBatchIndex + 1} of ${total}`;

    const titleEl = document.getElementById('examContentTitle');
    const hasTitle = !!(current.title && current.title.trim());
    titleEl.textContent = hasTitle ? current.title : '';
    titleEl.classList.toggle('hidden-element', !hasTitle);

    document.getElementById('examContentBody').textContent = current.content || '';

    const prevBtn = document.getElementById('examContentPrevBtn');
    const nextBtn = document.getElementById('examContentNextBtn');
    const continueBtn = document.getElementById('examContentContinueBtn');
    const isLast = examBatchIndex === total - 1;

    prevBtn.classList.toggle('hidden-element', examBatchIndex === 0);
    nextBtn.classList.toggle('hidden-element', isLast);
    continueBtn.classList.toggle('hidden-element', !isLast);

    prevBtn.onclick = () => {
        if (examBatchIndex === 0) return;
        examBatchIndex--;
        showExamContentBatch(items);
    };
    nextBtn.onclick = () => {
        if (examBatchIndex >= total - 1) return;
        examBatchIndex++;
        showExamContentBatch(items);
    };
    continueBtn.onclick = () => {
        viewer.classList.add('hidden-element');
        examStepIndex++;
        advanceExamPageSteps();
    };

    viewer.classList.remove('hidden-element');
}

// Renders the exam (preview or solve, form already decided) and starts the
// page walkthrough. Used by preview mode directly, and by solve mode once
// the attempt row is resolved.
function startExamView() {
    if (examQuestionsCache.length === 0) {
        document.getElementById('examAlreadyDoneNotice').textContent = 'This exam currently has no questions yet.';
        document.getElementById('examAlreadyDoneNotice').classList.remove('hidden-element');
        return;
    }
    renderExamQuestions();
    document.getElementById('examQuestionsWrapper').classList.remove('hidden-element');
    examPageSegments = buildExamPageSegments(examContentsCache, examQuestionsCache);
    goToExamPage(0);
}

// ============================================================================
// Collect whatever has been answered so far — no "required" validation
// (unlike the Evaluation form): a partial exam is a normal, valid
// submission, since the timer can cut it off mid-way.
// ============================================================================
function collectExamAnswers() {
    const answers = [];
    examQuestionsCache.forEach((q) => {
        if (q.question_type === 'text' || q.question_type === 'date' || q.question_type === 'time' || q.question_type === 'list') {
            const input = document.querySelector(`.cq-answer-input[data-qid="${q.id}"]`);
            if (input && input.value) answers.push({ question_id: q.id, answer_value: input.value });
        } else if (q.question_type === 'multiple_choice') {
            const checked = document.querySelector(`.cq-answer-radio[data-qid="${q.id}"]:checked`);
            if (checked) answers.push({ question_id: q.id, answer_value: checked.value });
        } else if (q.question_type === 'checkbox') {
            const checked = Array.from(document.querySelectorAll(`.cq-answer-checkbox[data-qid="${q.id}"]:checked`)).map(el => el.value);
            if (checked.length > 0) answers.push({ question_id: q.id, answer_value: checked });
        } else if (q.question_type === 'multiple_choice_grid' || q.question_type === 'checkbox_grid') {
            const rowMap = {};
            document.querySelectorAll(`.cq-answer-grid[data-qid="${q.id}"]:checked`).forEach(el => {
                const row = el.dataset.row;
                if (q.question_type === 'checkbox_grid') {
                    if (!rowMap[row]) rowMap[row] = [];
                    rowMap[row].push(el.value);
                } else {
                    rowMap[row] = el.value;
                }
            });
            if (Object.keys(rowMap).length > 0) answers.push({ question_id: q.id, answer_value: rowMap });
        }
    });
    return answers;
}

// ============================================================================
// SOLVE MODE — attempt lookup/create, countdown, submit/auto-submit.
// ============================================================================
// An answer only counts when something was actually filled in.
function isAnswerFilled(v) {
    if (v === null || v === undefined) return false;
    if (typeof v === 'string') return v.trim() !== '';
    if (Array.isArray(v)) return v.length > 0;
    if (typeof v === 'object') return Object.keys(v).length > 0;
    return true;
}

// Two kinds of exam. A PRE-REGISTRATION exam (require_before_registration)
// accepts whatever was answered — anything left blank simply scores 0. Any
// other exam (e.g. one required for a certificate) must be fully answered:
// it only counts once every question has an answer.
function examNeedsAllAnswers() {
    return !(exam && exam.require_before_registration);
}

// A submitted attempt only counts as a real, finished exam when EVERY
// question has a saved answer. An attempt that was auto-submitted empty (or
// cut off by the timer part-way) is not complete — the participant has to
// do the exam again (and the certificate stays locked until they do).
async function attemptIsComplete(attempt) {
    const { data: rows, error } = await client
        .from('activity_exam_answers')
        .select('question_id, answer_value')
        .eq('attempt_id', attempt.id);
    if (error) return true; // can't tell — never wipe someone's finished exam on a read error
    const answered = new Set((rows || []).filter(r => isAnswerFilled(r.answer_value)).map(r => r.question_id));
    if (examQuestionsCache.every(q => answered.has(q.id))) return true;
    // Time ran out and the page auto-submitted what had been answered: that
    // counts as finished (blanks score 0) as long as something was answered.
    // submitted_at at/after the deadline is what marks a timeout submission.
    const submittedAtMs = attempt.submitted_at ? new Date(attempt.submitted_at).getTime() : NaN;
    const deadlineMs = attempt.expires_at ? new Date(attempt.expires_at).getTime() : NaN;
    const timedOut = Number.isFinite(submittedAtMs) && Number.isFinite(deadlineMs) && submittedAtMs >= deadlineMs - 1000;
    return timedOut && answered.size > 0;
}

// Starts the same staff number over on the same attempt row (the unique
// "one row per staff number per exam" index stays satisfied): back to
// in_progress with a fresh start time/deadline. Old answer rows are cleared
// by submitExamAttempt when the new submission is saved.
async function restartAttempt(attempt) {
    const startedAt = new Date();
    const ONE_HUNDRED_YEARS_MS = 100 * 365 * 24 * 60 * 60 * 1000;
    const expiresAt = exam.timer_enabled
        ? new Date(startedAt.getTime() + (Number(exam.duration_seconds) || 1800) * 1000)
        : new Date(startedAt.getTime() + ONE_HUNDRED_YEARS_MS);
    const { data: updated, error } = await client
        .from('activity_exam_attempts')
        .update({
            status: 'in_progress',
            started_at: startedAt.toISOString(),
            expires_at: expiresAt.toISOString(),
            submitted_at: null,
            total_score: null,
            max_score: null
        })
        .eq('id', attempt.id)
        .select()
        .single();
    if (error) throw new Error(error.message);
    return updated;
}

async function startSolveMode() {
    if (!exam) return;

    let { data: attempt, error: attemptErr } = await client
        .from('activity_exam_attempts')
        .select('*')
        .eq('exam_id', exam.id)
        .ilike('staff_number', escapeLike(staffParam))
        .maybeSingle();

    if (attemptErr) {
        showFatalError('Something went wrong loading this exam. Please try again.');
        return;
    }

    if (attempt && attempt.status === 'submitted' && examNeedsAllAnswers() && !(await attemptIsComplete(attempt))) {
        // Submitted without answering every question (empty auto-submit, or
        // cut off by the timer) — doesn't count; start over.
        try {
            attempt = await restartAttempt(attempt);
        } catch (err) {
            showFatalError('Something went wrong restarting this exam. Please try again.');
            return;
        }
    }

    if (attempt && attempt.status === 'submitted') {
        document.getElementById('examAlreadyDoneNotice').textContent = "You've already completed this exam — taking you back to registration…";
        document.getElementById('examAlreadyDoneNotice').classList.remove('hidden-element');
        goToRegistrationAfterSuccess();
        return;
    }

    if (attempt && attempt.status === 'in_progress') {
        const expiresAt = new Date(attempt.expires_at).getTime();
        // For a no-timer exam, `expires_at` was stored as a far-future
        // timestamp when this attempt was created (see the brand-new-attempt
        // branch below) — so this is naturally never true for it, and the
        // attempt is never treated as expired. No separate timer_enabled
        // check is needed here for that reason.
        if (Date.now() > expiresAt) {
            if (examNeedsAllAnswers()) {
                // The page was closed (or the time ran out) before anything was
                // submitted. Nothing is saved while typing, so there is nothing
                // to keep — this is NOT turned into an empty "submitted" exam;
                // the participant simply starts the exam again.
                try {
                    attempt = await restartAttempt(attempt);
                } catch (err) {
                    showFatalError('Something went wrong restarting this exam. Please reopen this link to try again.');
                    return;
                }
            } else {
                // Pre-registration exam: time ran out with nothing submitted —
                // submitted as-is (every question scores 0) so the staff
                // number can move on to registration.
                try {
                    await submitExamAttempt(attempt, [], true);
                    document.getElementById('examAlreadyDoneNotice').textContent = "Time's up — your exam was submitted automatically. Taking you back to registration…";
                    document.getElementById('examAlreadyDoneNotice').classList.remove('hidden-element');
                    goToRegistrationAfterSuccess();
                } catch (err) {
                    showFatalError('Something went wrong finalizing your exam. Please reopen this link to try again — your in-progress attempt is still saved.');
                }
                return;
            }
        }
        currentAttempt = attempt;
        // No visible countdown, and no auto-submit-on-timeout, for a
        // no-timer exam — the participant submits manually via the Submit
        // button only.
        if (exam.timer_enabled) startCountdown(new Date(attempt.expires_at).getTime());
        startExamView();
        return;
    }

    // No attempt yet — start a brand new one. `expires_at` is fixed at
    // creation time from the exam's CURRENT duration_seconds; later edits to
    // the exam's duration never move an already-running attempt's deadline.
    // When the timer is disabled, `expires_at` is set to a far-future
    // timestamp instead (the column is NOT NULL) so this attempt is
    // effectively never "expired" anywhere it's checked (here, in
    // js/workshops.js's registration gate, and in exam-participants.js).
    const startedAt = new Date();
    const ONE_HUNDRED_YEARS_MS = 100 * 365 * 24 * 60 * 60 * 1000;
    const expiresAt = exam.timer_enabled
        ? new Date(startedAt.getTime() + (Number(exam.duration_seconds) || 1800) * 1000)
        : new Date(startedAt.getTime() + ONE_HUNDRED_YEARS_MS);

    const { data: newAttempt, error: insErr } = await client
        .from('activity_exam_attempts')
        .insert({
            exam_id: exam.id,
            course_id: exam.course_id,
            staff_number: staffParam,
            started_at: startedAt.toISOString(),
            expires_at: expiresAt.toISOString(),
            status: 'in_progress'
        })
        .select()
        .single();

    if (insErr) {
        // The unique index (one attempt per staff number per exam) is the
        // real backstop against a double-open from two near-simultaneous
        // tabs — re-check rather than showing a raw constraint error.
        if (insErr.code === '23505') {
            await startSolveMode();
            return;
        }
        showFatalError('Could not start this exam: ' + insErr.message);
        return;
    }

    currentAttempt = newAttempt;
    if (exam.timer_enabled) startCountdown(expiresAt.getTime());
    startExamView();
}

function startCountdown(expiresAtMs) {
    const wrapper = document.getElementById('examCountdownWrapper');
    const display = document.getElementById('examCountdownDisplay');
    wrapper.classList.remove('hidden-element');

    function tick() {
        const remainingMs = expiresAtMs - Date.now();
        if (remainingMs <= 0) {
            display.textContent = '00:00';
            clearInterval(countdownTimer);
            if (!autoSubmitting) {
                autoSubmitting = true;
                submitExamAttempt(currentAttempt, collectExamAnswers(), true).then(() => {
                    document.getElementById('examQuestionsWrapper').classList.add('hidden-element');
                    document.getElementById('examSuccessOverlay').classList.add('hidden-element');
                    document.getElementById('examAlreadyDoneNotice').textContent = "Time's up — your exam was submitted automatically with whatever you had answered. Taking you back to registration…";
                    document.getElementById('examAlreadyDoneNotice').classList.remove('hidden-element');
                    goToRegistrationAfterSuccess();
                }).catch(() => {
                    // Previously unhandled — a failure here used to vanish
                    // completely: no message, attempt stuck at 'in_progress'
                    // forever, nothing showing on the Exam Dashboard or Exam
                    // Scores for this participant. autoSubmitting is reset so
                    // reopening the exam link retries instead of being
                    // silently stuck with a dead Submit button.
                    autoSubmitting = false;
                    document.getElementById('examSubmitError').textContent = 'Time ran out, but your exam could not be submitted automatically. Please click Submit below to try again.';
                    document.getElementById('examSubmitError').classList.remove('hidden-element');
                });
            }
            return;
        }
        const totalSeconds = Math.ceil(remainingMs / 1000);
        const mm = String(Math.floor(totalSeconds / 60)).padStart(2, '0');
        const ss = String(totalSeconds % 60).padStart(2, '0');
        display.textContent = `${mm}:${ss}`;
    }
    tick();
    countdownTimer = setInterval(tick, 1000);
}

// Grades every question, writes activity_exam_answers, and flips the
// attempt to 'submitted'. Shared by the manual Submit button, the
// countdown's own auto-submit-at-zero, and the best-effort resume-when-
// already-expired path in startSolveMode.
async function submitExamAttempt(attempt, answers, isAuto) {
    const answerByQuestionId = new Map(answers.map(a => [a.question_id, a.answer_value]));
    let totalScore = 0;
    let maxScore = 0;

    const answerRows = examQuestionsCache.map(q => {
        maxScore += Number(q.points) || 0;
        const given = answerByQuestionId.has(q.id) ? answerByQuestionId.get(q.id) : null;
        const { is_correct, points_earned } = gradeExamAnswer(q, given);
        totalScore += points_earned;
        return {
            attempt_id: attempt.id,
            question_id: q.id,
            answer_value: given,
            is_correct,
            points_earned
        };
    });

    // Neither of these two writes was ever checked for an error — exactly
    // the same silent-failure shape found and fixed elsewhere this session
    // (create-exam.js/create-evaluation.js's question saves, workshops.js's
    // registration gate). A failure here previously left the attempt
    // sitting at status 'in_progress' forever with no error shown anywhere:
    // the participant saw a normal "Success" screen and got redirected, the
    // Exam Dashboard's "Responses"/"submitted" counts and Exam Scores never
    // picked it up (they only count rows that actually made it to
    // 'submitted'), and check-registration kept reporting the certificate's
    // required exam as still pending — all without a single visible error
    // anywhere. Now surfaced by throwing, which every caller below already
    // catches (or has been given a catch for).
    if (answerRows.length > 0) {
        // activity_exam_answers has no unique (attempt_id, question_id), so
        // a retry after a failed finalize (answers written, attempt update
        // failed) used to stack a second copy of every answer. Clearing this
        // attempt's earlier rows first makes a retry safe.
        const { error: clearErr } = await client.from('activity_exam_answers').delete().eq('attempt_id', attempt.id);
        if (clearErr) throw new Error('Could not save your answers: ' + clearErr.message);
        const { error: answersErr } = await client.from('activity_exam_answers').insert(answerRows);
        if (answersErr) throw new Error('Could not save your answers: ' + answersErr.message);
    }

    // `.select('id, status')` makes the update report the rows it actually
    // changed: a plain update that matches 0 rows (blocked by a policy, row
    // gone) returns NO error, so the participant used to get the success
    // screen while the attempt stayed 'in_progress' — later shown as
    // "Expired" with all the answers sitting saved. Now that case throws too.
    const { data: finalizedRows, error: updateErr } = await client.from('activity_exam_attempts').update({
        status: 'submitted',
        submitted_at: new Date().toISOString(),
        total_score: totalScore,
        max_score: maxScore
    }).eq('id', attempt.id).select('id, status');
    if (updateErr) throw new Error('Could not finalize your submission: ' + updateErr.message);
    if (!finalizedRows || finalizedRows.length === 0 || finalizedRows[0].status !== 'submitted') {
        throw new Error('Could not finalize your submission: the exam record was not updated.');
    }

    if (countdownTimer) clearInterval(countdownTimer);
}

document.getElementById('examSubmitBtn').addEventListener('click', async () => {
    if (previewMode) {
        alert('This is preview mode — nothing is submitted or recorded here.');
        return;
    }
    if (!exam || !currentAttempt || autoSubmitting) return;

    const btn = document.getElementById('examSubmitBtn');

    // Every question must be answered before a manual submit counts —
    // except in a pre-registration exam, where blanks are allowed (they
    // score 0) after an explicit "are you sure?" confirmation.
    const givenAnswers = collectExamAnswers();
    const answeredIds = new Set(givenAnswers.filter(a => isAnswerFilled(a.answer_value)).map(a => a.question_id));
    const missingNumbers = [];
    examQuestionsCache.forEach((q, idx) => { if (!answeredIds.has(q.id)) missingNumbers.push(idx + 1); });
    if (missingNumbers.length > 0) {
        if (examNeedsAllAnswers()) {
            const errBox = document.getElementById('examSubmitError');
            errBox.textContent = `Please answer every question before submitting. Not answered yet: question ${missingNumbers.join(', ')}.`;
            errBox.classList.remove('hidden-element');
            return;
        }
        document.getElementById('examConfirmMessage').textContent =
            `You have not answered question ${missingNumbers.join(', ')}. Unanswered questions will score 0. Are you sure you want to submit?`;
        pendingConfirmedAnswers = givenAnswers;
        document.getElementById('examConfirmOverlay').classList.remove('hidden-element');
        return;
    }
    await finishManualSubmit(givenAnswers);
});

let pendingConfirmedAnswers = null;

document.getElementById('examConfirmNoBtn').addEventListener('click', () => {
    pendingConfirmedAnswers = null;
    document.getElementById('examConfirmOverlay').classList.add('hidden-element');
});

document.getElementById('examConfirmYesBtn').addEventListener('click', async () => {
    const answers = pendingConfirmedAnswers;
    pendingConfirmedAnswers = null;
    document.getElementById('examConfirmOverlay').classList.add('hidden-element');
    if (!answers || !exam || !currentAttempt || autoSubmitting) return;
    await finishManualSubmit(answers);
});

async function finishManualSubmit(givenAnswers) {
    const btn = document.getElementById('examSubmitBtn');
    document.getElementById('examSubmitError').classList.add('hidden-element');

    btn.disabled = true;
    const originalText = btn.textContent;
    btn.textContent = 'Submitting…';

    try {
        autoSubmitting = true;
        await submitExamAttempt(currentAttempt, givenAnswers, false);
        document.getElementById('examQuestionsWrapper').classList.add('hidden-element');
        document.getElementById('examCountdownWrapper').classList.add('hidden-element');
        document.getElementById('examSuccessOverlay').classList.remove('hidden-element');
        goToRegistrationAfterSuccess();
    } catch (err) {
        console.error('Exam submit failed:', err);
        document.getElementById('examSubmitError').textContent = 'Something went wrong submitting your answers. Please try again.' + (err && err.message ? ' (' + err.message + ')' : '');
        document.getElementById('examSubmitError').classList.remove('hidden-element');
        autoSubmitting = false;
    } finally {
        btn.disabled = false;
        btn.textContent = originalText;
    }
}


// The whole point of this exam is that it sits in front of registration
// (js/workshops.js's gate only ever sends someone here with mode=solve when
// their registration is blocked on it) — so once they've submitted, the
// natural next step is straight back into the registration form for the
// same activity, already past the staff-number step, not a dead end they
// have to navigate away from manually. register.html's own
// applyDirectCourseLinkFromUrl()/applyStaffNumberFromUrl() already know how
// to pick this straight back up from these two params alone: the course
// stays locked to this activity and the staff number gate auto-continues,
// landing exactly on the (now unblocked) registration form.
function buildReturnToRegistrationUrl() {
    const url = new URL('register.html', window.location.href);
    if (registrationToken) url.searchParams.set('c', registrationToken);
    else url.searchParams.set('course', String(exam.course_id));
    url.searchParams.set('staff', staffParam);
    return url.toString();
}

function goToRegistrationAfterSuccess() {
    const REDIRECT_DELAY_MS = 1800; // long enough to read "submitted", short enough to feel immediate
    setTimeout(() => { window.location.href = buildReturnToRegistrationUrl(); }, REDIRECT_DELAY_MS);
}

// Manual "Continue to Registration" click jumps straight there instead of
// waiting out the auto-redirect timer above.
document.getElementById('examSuccessCloseBtn')?.addEventListener('click', () => {
    window.location.href = buildReturnToRegistrationUrl();
});

init();

// Prepares a typed staff number for .ilike(): removes invisible direction/zero-width marks, converts Arabic digits
// to 0-9, then escapes LIKE wildcards so "%" or "_" match only themselves (exact, case-insensitive match).
function escapeLike(value) {
    const cleaned = String(value == null ? "" : value)
        .replace(/[\u200B-\u200F\u202A-\u202E\u2060-\u2069\uFEFF\u00AD]/g, "")
        .replace(/[\u0660-\u0669]/g, (d) => String(d.charCodeAt(0) - 0x0660))
        .replace(/[\u06F0-\u06F9]/g, (d) => String(d.charCodeAt(0) - 0x06F0))
        .trim();
    return cleaned.replace(/[\\%_]/g, (m) => "\\" + m);
}

